# version: '3'

services:
  
  postgres:
    image: postgres
    container_name: "postgres"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: postgres_db
    ports:
      - "15432:5432"
    volumes:
      - postgres:/var/lib/postgres/data
    restart: unless-stopped
    networks:
      - postgres-compose-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: "pgadmin4"
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: test@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: test123
    volumes:
      - postgres:/var/lib/pgadmin/data
    restart: unless-stopped
    networks:
      - postgres-compose-network

volumes:
  postgres:

networks: 
  postgres-compose-network:
    driver: bridge