version: '3'

services:
  
  postgres:
    image: postgres
    container_name: "postgres"
    #hostname: postgres
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: postgres_db
    volumes:
      - ./postgres-data/var/lib/postgresql/data§§
    restart: unless-stopped
    networks:
      - postgres-compose-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: "pgadmin4"
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: test@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: test123
    #environment: "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - ./postgres-data/var/lib/pgadmin4/data
    restart: unless-stopped
    networks:
      - postgres-compose-network

volumes:
  postgres-data:

networks: 
  postgres-compose-network:
    driver: bridge